name: Deploy to server

on:
  push:
    branches: ["main"]

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      getaway: ${{ steps.getaway-step.outputs.my_output }}
    steps:
      - name: Action
        uses: actions/checkout@v4

      - name: Set Output
        id: getaway-step
        run: echo "my_output=Getaway Active" >> $GITHUB_OUTPUT

  second_job:
    needs: first_job
    if: ${{ needs.first_job.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Second Job
        run: echo "First Job succeeded, hence, you have Second Job."

      - name: Obtaining Data from outputs
        run: |
          echo "Output from first_job:"
          echo "${{ needs.first_job.outputs.getaway }}"
