name: Deploy to server

on:
  push:
    branches: ["main"]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run:  echo "Hello World!"

  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Second Job
        run:  echo "Second Job!"
