name: Deploy to server

on:
  push:
    branches: ["main"]

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      getaway: ${{ steps.getaway-step.outputs.my_output }}
    steps:
      - name: Set Output
        id: getaway-step
        run: echo "my_output=Getaway Active" >> $GITHUB_OUTPUT

  second_job:
    needs: first_job
    if: ${{ needs.first_job.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Output Debug
        run: echo "Output from first_job: ${{ needs.first_job.outputs.getaway }}"
