name: Deploy to server

on:
  push:
    branches: ["main"]

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      NAME: "1492"
    steps:
      - name: First Job
        run:  echo "Hello from $NAME"

  second_job:
    needs: first_job
    if: ${{ needs.first_job.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Second Job
        run:  echo "First Job succeseded, hence, you have Second Job."
